name: Validate lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint code
        run: npm run lint
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
