name: Validate pull-request title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request title rules
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          CONVENTIONAL_COMMIT_REGEXP: "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\\([^)]+\\))?: .+"
        run: |
          if [[ ! "$PR_TITLE" =~ $CONVENTIONAL_COMMIT_REGEXP ]]; then
            echo "Invalid PR title. Please follow the Conventional Commits format."
            exit 1
          fi
